### ISSUE TITLE
Validate new issue action in hydrated projects

### ISSUE THREAD

**Issue by delucchi-cmu** [LSSTDESC/RAIL-project-template#15]
There's an action within this project (add-issue-to-project) that requires a repo secret, but wasn't copied over from the LINCC Frameworks repo. 

It would be nice for the action to work in this repo.

Further, it would be good to include a similar action in hydrated projects that will copy those issues into a common RAIL project tracker.

**Comment by drewoldag** [comment]
I created a new Personal Access Token and added it to this repositories secrets.

I followed the instructions here: https://github.com/actions/add-to-project#creating-a-pat-and-adding-it-to-your-repository

**Comment by drewoldag** [comment]
Verified that new issues created in this repo will be automatically added to the LINCC Frameworks project tracker.

**Comment by drewoldag** [comment]
Accidentally pushed this directly to main. Subsequently set up pre-commit to avoid this in the future. 

The file: https://github.com/LSSTDESC/RAIL-project-template/blob/main/python-project-template/.github/workflows/add-issue-to-project-tracker.yml

The PR setting up pre-commit: https://github.com/LSSTDESC/RAIL-project-template/pull/18
