### ISSUE TITLE
Prepare to remove the pull_request_template.md file

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/RAIL-project-template#23]
Doesn't sound like there's a lot of support for the PR template. It's open for discussion, but it's likely that we'll receive a request to remove it.

**Comment by eacharles** [comment]
Let's take a poll with some options:

1. remove it,
2. reduce it to a much short checklist
3. leave it as is
4. modify it

**Comment by aimalz** [comment]
closed by #29
